In [4]:
from torchvision import models

en = models.efficientnet_b0(pretrained=True)
en.requires_grad_(False)

EfficientNet(
  (features): Sequential(
    (0): ConvNormActivation(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): SiLU(inplace=True)
    )
    (1): Sequential(
      (0): MBConv(
        (block): Sequential(
          (0): ConvNormActivation(
            (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
            (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): SiLU(inplace=True)
          )
          (1): SqueezeExcitation(
            (avgpool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
            (fc2): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
            (activation): SiLU(inplace=True)
            (scale_activation): Sigmoid()
          )
          (2): ConvNormActivation(
 

In [5]:
from torch import nn

f = nn.Sequential(*list(en.children())[:-1])

In [38]:
import torch
x = torch.rand((1, 3, 28, 28))
f.eval()
f(x).squeeze().shape

torch.Size([1280])

In [6]:
f.parameters().__next__().requires_grad

False

In [9]:
from torchvision import transforms
from PIL import Image

tfms = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ]
)

pretrained = True
efficientnet = models.efficientnet_b3(pretrained=pretrained)
embedding = nn.Sequential(*list(efficientnet.children())[:-1])


embedding(tfms(Image.open('../food/00000.jpg')).unsqueeze(0)).squeeze().detach().numpy()

(1536,)

In [61]:
import torch
import numpy as np


embeddings = torch.empty((3, 1536))
x = list()

with torch.no_grad():
    for i in range(3):
        path = '../food/' + str(i).rjust(5, '0') + '.jpg'
        x.append(tfms(Image.open(path)).unsqueeze(0))
        embeddings[i] = embedding(tfms(Image.open(path)).unsqueeze(0)).squeeze()


In [24]:
torch.concat(tuple(embeddings)).shape

torch.Size([4608])

In [29]:
embeddings[0].size(0)

1536

In [35]:
embedding(x[0])

tensor([[[[0.1777]],

         [[0.1324]],

         [[0.2429]],

         ...,

         [[0.1686]],

         [[0.2289]],

         [[0.2119]]]], grad_fn=<MeanBackward1>)

In [75]:
import os
import torch
from torch import nn
import torch.nn.functional as F
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader, random_split
import pytorch_lightning as pl


dataset = MNIST(os.getcwd(), download=True, transform=transforms.ToTensor())
train_loader = DataLoader(dataset, batch_size=3)


In [76]:
iter(train_loader).next()

[tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]]]),
 tensor([5, 0, 4])]

In [97]:
# with open('../triplets.txt', 'w') as f:
#     for triplet in triplets:
#         f.writelines(' '.join(triplet) + " " + str(1) + "\n")
#         triplet[1], triplet[2] = triplet[2], triplet[1]
#         f.writelines(' '.join(triplet) + " " + str(0) + "\n")    

In [89]:
triplets

[['02461', '03450', '02678'],
 ['02299', '02499', '04987'],
 ['04663', '01056', '03029'],
 ['04532', '01186', '01297'],
 ['03454', '03809', '02204'],
 ['02851', '03047', '00524'],
 ['01168', '00262', '02663'],
 ['02134', '04969', '01153'],
 ['02741', '02851', '01518'],
 ['04668', '02527', '03481'],
 ['02183', '02123', '03862'],
 ['00336', '02052', '03152'],
 ['02227', '04152', '04429'],
 ['01298', '01362', '01251'],
 ['01810', '03113', '02064'],
 ['00521', '01243', '04907'],
 ['04847', '03701', '01838'],
 ['04321', '03785', '00420'],
 ['00062', '01531', '03849'],
 ['03861', '03572', '01937'],
 ['02736', '02429', '04730'],
 ['00826', '03953', '01855'],
 ['02171', '00898', '02225'],
 ['02073', '03504', '03072'],
 ['03745', '03661', '04041'],
 ['02800', '00070', '04055'],
 ['00711', '04421', '01413'],
 ['00564', '04183', '01869'],
 ['02662', '00681', '01339'],
 ['01579', '00797', '04855'],
 ['01033', '00400', '01576'],
 ['02185', '04652', '04540'],
 ['00037', '00977', '04665'],
 ['01372',

In [102]:
img_dir = '../food'
triplets_path = '../triplets.txt'

tfms = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ]
)

In [106]:
with open(triplets_path) as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]


triplet, label = triplets[0][:-1], triplets[-1]
paths = [os.path.join(img_dir, f"{i}.jpg") for i in triplet]
images = [Image.open(path) for path in paths]

if tfms:
    images = [tfms(image).unsqueeze(0) for image in images]

embeddings = [embedding(t).squeeze() for t in images]
phi = torch.concat(tuple(embeddings))


In [113]:
from functools import lru_cache

In [128]:
class House():
    def __init__(self, path):
        self.img = Image.open(path)

    @lru_cache
    def f(self):
        for i in range(100):
            embedding(tfms(self.img).unsqueeze(0)).squeeze()
        return embedding(tfms(self.img).unsqueeze(0)).squeeze()

In [129]:
h = House('../food/00000.jpg')

In [131]:
h.f()

tensor([0.1170, 0.1664, 0.1976,  ..., 0.1184, 0.1103, 0.1558],
       grad_fn=<SqueezeBackward0>)

In [134]:
img = Image.open('../food/00000.jpg')

def f():
    for i in range(20):
        embedding(tfms(img).unsqueeze(0)).squeeze()
    return embedding(tfms(img).unsqueeze(0)).squeeze()

In [135]:
f()

tensor([0.2162, 0.0513, 0.0648,  ..., 0.1543, 0.2104, 0.2552],
       grad_fn=<SqueezeBackward0>)

In [136]:
f = lru_cache(f, maxsize=512)

In [138]:
f()

tensor([0.2163, 0.1350, 0.2351,  ..., 0.1492, 0.1949, 0.1736],
       grad_fn=<SqueezeBackward0>)

In [3]:
img_dir = "../food"
triplets_path = "../triplets.txt"

with open(triplets_path) as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]

In [9]:
from sklearn.model_selection import train_test_split

train_triplets, val_triplets = train_test_split(triplets, test_size=0.1, random_state=489, shuffle=True)

In [11]:
with open('train_triplets_split.txt', 'w') as f:
    for item in train_triplets:
        f.writelines(" ".join(item) + "\n")

with open('val_triplets_split.txt', 'w') as f:
    for item in val_triplets:
        f.writelines(" ".join(item) + "\n")

In [13]:
img_dir = "../food"
train_triplets_path = "../triplets.txt"
train_split_path = "../train_split.txt"
val_split_path = "../val_split.txt"

with open(train_triplets_path) as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]

train_triplets, val_triplets = train_test_split(triplets, test_size=0.1, random_state=489, shuffle=True)

with open(train_split_path, 'w') as f:
    for item in train_triplets:
        f.writelines(" ".join(item) + "\n")

with open(val_split_path, 'w') as f:
    for item in val_triplets:
        f.writelines(" ".join(item) + "\n")

In [17]:
img_dir = "../food"
train_triplets_path = "../train_triplets.txt"
triplets_path = "../triplets.txt"
train_split_path = "../train_split.txt"
val_split_path = "../val_split.txt"

with open(train_triplets_path, 'r') as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]

with open(triplets_path, 'w') as f:
    for triplet in triplets:
        f.writelines(' '.join(triplet) + " " + str(1) + "\n")
        triplet[1], triplet[2] = triplet[2], triplet[1]
        f.writelines(' '.join(triplet) + " " + str(0) + "\n") 
    
with open(triplets_path, 'r') as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]

train_triplets, val_triplets = train_test_split(triplets, test_size=0.1, random_state=489, shuffle=True)

with open(train_split_path, 'w') as f:
    for item in train_triplets:
        f.writelines(" ".join(item) + "\n")

with open(val_split_path, 'w') as f:
    for item in val_triplets:
        f.writelines(" ".join(item) + "\n")

In [28]:
from torchvision.io import read_image

img = read_image('../food/00000.jpg')

In [29]:
from PIL import Image

img = Image.open('../food/00000.jpg')

In [39]:
from PIL import Image
import torch
from torch import nn
from torchvision import transforms, models
from torch.utils.data import Dataset, DataLoader


class TripletsDataset(Dataset):
    def __init__(self, triplets_path, img_dir, transform=None):
        self.triplets_path = triplets_path
        self.img_dir = img_dir
        self.transform = transform

        with open(self.triplets_path) as f:
            triplets = f.readlines()
        triplets = [triplet.strip().split(" ") for triplet in triplets]
        self.labels = [int(triplet[-1]) for triplet in triplets]
        self.triplets = [triplet[:-1] for triplet in triplets]

    def __len__(self):
        return len(self.triplets)

    def __getitem__(self, idx):
        triplet = self.triplets[idx]
        label = self.labels[idx]
        label = torch.tensor(label)

        paths = [os.path.join(self.img_dir, f"{i}.jpg") for i in triplet]
        images = [Image.open(path) for path in paths]

        if self.transform:
            images = [self.transform(image) for image in images]

        return images, label


In [54]:
import os
from torch import nn
from torchvision import models
import torch.nn.functional as F
from torch.optim import SGD
import pytorch_lightning as pl


class Classifier(pl.LightningModule):
    def __init__(self):
        super().__init__()

        self.efficientnet = models.efficientnet_b0(pretrained=True)
        self.embedding = nn.Sequential(
            *list(self.efficientnet.children())[:-1]
        )  # this excludes the classification layer of efficientnet
        self.embedding.requires_grad_(False)  # no fine-tuning

        self.classifier = nn.Sequential(
            nn.Linear(in_features=3 * 1280, out_features=100),
            nn.ReLU(),
            nn.Dropout(p=0.5, inplace=True),
            nn.Linear(100, 2),
        ) # the calssifier we are training

        self.loss = nn.CrossEntropyLoss()

    def forward(self, images):
        img_a, img_b, img_c = images

        phi_a = self.embedding(img_a).squeeze()
        phi_b = self.embedding(img_b).squeeze()
        phi_c = self.embedding(img_c).squeeze()
        phi = torch.concat((phi_a, phi_b, phi_c), dim=1)

        print(phi.shape)
        y_hat = self.classifier(phi)

        return y_hat

    def configure_optimizers(self):
        return SGD(self.parameters(), lr=1e-3, weight_decay=1e-3)

    def training_step(self, batch):
        x, y = batch
        # x = x.view(x.size(0), -1)
        y_hat = self(x)
        loss = self.loss(y_hat, y)

        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


In [61]:
img_dir = "../food"
train_triplets_path = "../train_triplets.txt"
triplets_path = "../triplets.txt"
train_split_path = "../train_split.txt"
val_split_path = "../val_split.txt"

AVAIL_GPUS = min(1, torch.cuda.device_count())
batch_size = 8
num_workers = 8

# get triplets
with open(train_triplets_path) as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]

# for each triplet we create two samples and write to a new txt file:
#  - one for the original triplet; with label 1
#  - one with the second and third image swapped; with label 0
with open(triplets_path, "w") as f:
    for triplet in triplets:
        f.writelines(" ".join(triplet) + " " + str(1) + "\n")
        triplet[1], triplet[2] = triplet[2], triplet[1]
        f.writelines(" ".join(triplet) + " " + str(0) + "\n")
with open(triplets_path, "r") as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]

# split into training and validation set
train_triplets, val_triplets = train_test_split(
    triplets, test_size=0.1, random_state=489, shuffle=True
)

# write training and validation set to txt (so that DataSet can access it)
with open(train_split_path, "w") as f:
    for item in train_triplets:
        f.writelines(" ".join(item) + "\n")
with open(val_split_path, "w") as f:
    for item in val_triplets:
        f.writelines(" ".join(item) + "\n")


tfms = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ]
)  # could also try augmentation

train_dataset = TripletsDataset(train_split_path, img_dir, tfms)
val_dataset = TripletsDataset(val_split_path, img_dir, tfms)

train_dataloader = DataLoader(
    dataset=train_dataset, batch_size=batch_size, num_workers=num_workers
)
val_dataloader = DataLoader(
    dataset=val_dataset, batch_size=batch_size, num_workers=num_workers
)
model = Classifier()

In [62]:
images_batch = iter(train_dataloader).next()

In [63]:
model(images_batch[0])

torch.Size([8, 3840])


tensor([[ 0.0228, -0.0512],
        [ 0.3207, -0.0761],
        [ 0.0933, -0.1198],
        [ 0.1666, -0.2643],
        [ 0.2849, -0.1125],
        [ 0.1254, -0.1547],
        [ 0.0736, -0.0026],
        [ 0.3086,  0.0059]], grad_fn=<AddmmBackward0>)

In [1]:


with open("/home/fabio/Code/iml/iml-projects/Fabio/task3/test_triplets.txt") as f:
    triplets = f.readlines()
triplets = [triplet.strip().split(" ") for triplet in triplets]

In [1]:
with open("../train_triplets.txt") as f:
    train_triplets = f.readlines()
train_triplets = [x.strip() for x in train_triplets]

In [2]:
train_triplets[:5]

['02461 03450 02678',
 '02299 02499 04987',
 '04663 01056 03029',
 '04532 01186 01297',
 '03454 03809 02204']

In [3]:
train_triplets_splitted = np.array(
    [["00000"] * 3] * len(train_triplets)
) 

In [6]:
train_triplets_splitted[:5]

array([['02461', '03450', '02678'],
       ['02299', '02499', '04987'],
       ['04663', '01056', '03029'],
       ['04532', '01186', '01297'],
       ['03454', '03809', '02204']], dtype='<U5')

In [5]:
for i in range(len(train_triplets)):
    train_triplets_splitted[i, :] = np.array(train_triplets[i].split())


In [ ]:
from torch.linalg import norm